// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kvstore/v1/kv.proto

package com.github.mxplusb.pleiades.api.kvstore.v1;

public interface GetBucketDescriptorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kvstore.v1.GetBucketDescriptorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.kvstore.v1.BucketDescriptor bucket_descriptor = 1 [json_name = "bucketDescriptor"];</code>
   * @return Whether the bucketDescriptor field is set.
   */
  boolean hasBucketDescriptor();
  /**
   * <code>.kvstore.v1.BucketDescriptor bucket_descriptor = 1 [json_name = "bucketDescriptor"];</code>
   * @return The bucketDescriptor.
   */
  com.github.mxplusb.pleiades.api.kvstore.v1.BucketDescriptor getBucketDescriptor();
  /**
   * <code>.kvstore.v1.BucketDescriptor bucket_descriptor = 1 [json_name = "bucketDescriptor"];</code>
   */
  com.github.mxplusb.pleiades.api.kvstore.v1.BucketDescriptorOrBuilder getBucketDescriptorOrBuilder();
}
