---
apiVersion: apps/host
kind: Deployment
metadata:
  name: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 1 # You could also consider elastic scaling for this deployment
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            # Points cloudflared to the host file, which configures what
            # cloudflared will actually do. This file is created by a ConfigMap
            # below.
            - --host
            - /etc/cloudflared/host/host.yaml
            - run
          livenessProbe:
            httpGet:
              # Cloudflared has a /ready endpoint which returns 200 if and only if
              # it has an active connection to the edge.
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: host
              mountPath: /etc/cloudflared/host
              readOnly: true
            # Each tunnel has an associated "credentials file" which authorizes machines
            # to run the tunnel. cloudflared will read this file from its local filesystem,
            # and it'll be stored in a k8s secret.
            - name: creds
              mountPath: /etc/cloudflared/creds
              readOnly: true
      volumes:
        - name: creds
          secret:
            # By default, the credentials file will be created under ~/.cloudflared/<tunnel ID>.json
            # when you run `cloudflared tunnel create`. You can move it into a secret by using:
            # ```sh
            # kubectl create secret generic tunnel-credentials \
            # --from-file=credentials.json=/Users/yourusername/.cloudflared/<tunnel ID>.json
            # ```
            secretName: tunnel-credentials
        # Create a host.yaml file from the ConfigMap below.
        - name: host
          configMap:
            name: cloudflared
            items:
              - key: host.yaml
                path: host.yaml
---
apiVersion: host
kind: ConfigMap
metadata:
  name: cloudflared
data:
  config.yaml: |
    tunnel: 27fe2708-f301-4129-87f7-8b1634bb1a64
    credentials-file: /etc/cloudflared/creds/credentials.json
    # Serves the metrics server under /metrics and the readiness server under /ready
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    originRequest:
      noTLSVerify: true
    ingress:
    - hostname: ci.r3t.io
      service: http://concourse-web.concourse.svc.cluster.local:8080
    - service: http_status:404