// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft/v1/raft_host.proto

package io.a13s.api.raft.v1;

public interface GetHostConfigResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:raft.v1.GetHostConfigResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.raft.v1.HostConfig config = 1 [json_name = "config"];</code>
   * @return Whether the config field is set.
   */
  boolean hasConfig();
  /**
   * <code>.raft.v1.HostConfig config = 1 [json_name = "config"];</code>
   * @return The config.
   */
  io.a13s.api.raft.v1.HostConfig getConfig();
  /**
   * <code>.raft.v1.HostConfig config = 1 [json_name = "config"];</code>
   */
  io.a13s.api.raft.v1.HostConfigOrBuilder getConfigOrBuilder();
}
