// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft/v1/raft_event.proto

package io.a13s.api.raft.v1;

public interface RaftEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:raft.v1.RaftEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.raft.v1.EventType typ = 1 [json_name = "typ"];</code>
   * @return The enum numeric value on the wire for typ.
   */
  int getTypValue();
  /**
   * <code>.raft.v1.EventType typ = 1 [json_name = "typ"];</code>
   * @return The typ.
   */
  io.a13s.api.raft.v1.EventType getTyp();

  /**
   * <code>.raft.v1.Event action = 2 [json_name = "action"];</code>
   * @return The enum numeric value on the wire for action.
   */
  int getActionValue();
  /**
   * <code>.raft.v1.Event action = 2 [json_name = "action"];</code>
   * @return The action.
   */
  io.a13s.api.raft.v1.Event getAction();

  /**
   * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
   * @return The timestamp.
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

  /**
   * <code>.raft.v1.RaftLogEntryEvent log_entry = 4 [json_name = "logEntry"];</code>
   * @return Whether the logEntry field is set.
   */
  boolean hasLogEntry();
  /**
   * <code>.raft.v1.RaftLogEntryEvent log_entry = 4 [json_name = "logEntry"];</code>
   * @return The logEntry.
   */
  io.a13s.api.raft.v1.RaftLogEntryEvent getLogEntry();
  /**
   * <code>.raft.v1.RaftLogEntryEvent log_entry = 4 [json_name = "logEntry"];</code>
   */
  io.a13s.api.raft.v1.RaftLogEntryEventOrBuilder getLogEntryOrBuilder();

  /**
   * <code>.raft.v1.RaftSnapshotEvent snapshot = 5 [json_name = "snapshot"];</code>
   * @return Whether the snapshot field is set.
   */
  boolean hasSnapshot();
  /**
   * <code>.raft.v1.RaftSnapshotEvent snapshot = 5 [json_name = "snapshot"];</code>
   * @return The snapshot.
   */
  io.a13s.api.raft.v1.RaftSnapshotEvent getSnapshot();
  /**
   * <code>.raft.v1.RaftSnapshotEvent snapshot = 5 [json_name = "snapshot"];</code>
   */
  io.a13s.api.raft.v1.RaftSnapshotEventOrBuilder getSnapshotOrBuilder();

  /**
   * <code>.raft.v1.RaftConnectionEvent connection = 6 [json_name = "connection"];</code>
   * @return Whether the connection field is set.
   */
  boolean hasConnection();
  /**
   * <code>.raft.v1.RaftConnectionEvent connection = 6 [json_name = "connection"];</code>
   * @return The connection.
   */
  io.a13s.api.raft.v1.RaftConnectionEvent getConnection();
  /**
   * <code>.raft.v1.RaftConnectionEvent connection = 6 [json_name = "connection"];</code>
   */
  io.a13s.api.raft.v1.RaftConnectionEventOrBuilder getConnectionOrBuilder();

  /**
   * <code>.raft.v1.RaftNodeEvent node = 7 [json_name = "node"];</code>
   * @return Whether the node field is set.
   */
  boolean hasNode();
  /**
   * <code>.raft.v1.RaftNodeEvent node = 7 [json_name = "node"];</code>
   * @return The node.
   */
  io.a13s.api.raft.v1.RaftNodeEvent getNode();
  /**
   * <code>.raft.v1.RaftNodeEvent node = 7 [json_name = "node"];</code>
   */
  io.a13s.api.raft.v1.RaftNodeEventOrBuilder getNodeOrBuilder();

  /**
   * <code>.raft.v1.RaftHostShutdown host_shutdown = 8 [json_name = "hostShutdown"];</code>
   * @return Whether the hostShutdown field is set.
   */
  boolean hasHostShutdown();
  /**
   * <code>.raft.v1.RaftHostShutdown host_shutdown = 8 [json_name = "hostShutdown"];</code>
   * @return The hostShutdown.
   */
  io.a13s.api.raft.v1.RaftHostShutdown getHostShutdown();
  /**
   * <code>.raft.v1.RaftHostShutdown host_shutdown = 8 [json_name = "hostShutdown"];</code>
   */
  io.a13s.api.raft.v1.RaftHostShutdownOrBuilder getHostShutdownOrBuilder();

  public io.a13s.api.raft.v1.RaftEvent.EventCase getEventCase();
}
