// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.3.0
// source: raft_server.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RaftConfigServiceClient is the client API for RaftConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaftConfigServiceClient interface {
	PutConfiguration(ctx context.Context, in *PutRaftConfigRequest, opts ...grpc.CallOption) (*NewRaftConfigResponse, error)
	GetConfiguration(ctx context.Context, in *GetRaftConfigRequest, opts ...grpc.CallOption) (*GetRaftConfigResponse, error)
	ListConfigurations(ctx context.Context, in *ListRaftConfigsRequest, opts ...grpc.CallOption) (*ListRaftConfigsResponse, error)
}

type raftConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftConfigServiceClient(cc grpc.ClientConnInterface) RaftConfigServiceClient {
	return &raftConfigServiceClient{cc}
}

func (c *raftConfigServiceClient) PutConfiguration(ctx context.Context, in *PutRaftConfigRequest, opts ...grpc.CallOption) (*NewRaftConfigResponse, error) {
	out := new(NewRaftConfigResponse)
	err := c.cc.Invoke(ctx, "/RaftConfigService/PutConfiguration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftConfigServiceClient) GetConfiguration(ctx context.Context, in *GetRaftConfigRequest, opts ...grpc.CallOption) (*GetRaftConfigResponse, error) {
	out := new(GetRaftConfigResponse)
	err := c.cc.Invoke(ctx, "/RaftConfigService/GetConfiguration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftConfigServiceClient) ListConfigurations(ctx context.Context, in *ListRaftConfigsRequest, opts ...grpc.CallOption) (*ListRaftConfigsResponse, error) {
	out := new(ListRaftConfigsResponse)
	err := c.cc.Invoke(ctx, "/RaftConfigService/ListConfigurations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftConfigServiceServer is the server API for RaftConfigService service.
// All implementations must embed UnimplementedRaftConfigServiceServer
// for forward compatibility
type RaftConfigServiceServer interface {
	PutConfiguration(context.Context, *PutRaftConfigRequest) (*NewRaftConfigResponse, error)
	GetConfiguration(context.Context, *GetRaftConfigRequest) (*GetRaftConfigResponse, error)
	ListConfigurations(context.Context, *ListRaftConfigsRequest) (*ListRaftConfigsResponse, error)
	mustEmbedUnimplementedRaftConfigServiceServer()
}

// UnimplementedRaftConfigServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRaftConfigServiceServer struct {
}

func (UnimplementedRaftConfigServiceServer) PutConfiguration(context.Context, *PutRaftConfigRequest) (*NewRaftConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutConfiguration not implemented")
}
func (UnimplementedRaftConfigServiceServer) GetConfiguration(context.Context, *GetRaftConfigRequest) (*GetRaftConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfiguration not implemented")
}
func (UnimplementedRaftConfigServiceServer) ListConfigurations(context.Context, *ListRaftConfigsRequest) (*ListRaftConfigsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConfigurations not implemented")
}
func (UnimplementedRaftConfigServiceServer) mustEmbedUnimplementedRaftConfigServiceServer() {}

// UnsafeRaftConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftConfigServiceServer will
// result in compilation errors.
type UnsafeRaftConfigServiceServer interface {
	mustEmbedUnimplementedRaftConfigServiceServer()
}

func RegisterRaftConfigServiceServer(s grpc.ServiceRegistrar, srv RaftConfigServiceServer) {
	s.RegisterService(&RaftConfigService_ServiceDesc, srv)
}

func _RaftConfigService_PutConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRaftConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftConfigServiceServer).PutConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RaftConfigService/PutConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftConfigServiceServer).PutConfiguration(ctx, req.(*PutRaftConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftConfigService_GetConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRaftConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftConfigServiceServer).GetConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RaftConfigService/GetConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftConfigServiceServer).GetConfiguration(ctx, req.(*GetRaftConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftConfigService_ListConfigurations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRaftConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftConfigServiceServer).ListConfigurations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RaftConfigService/ListConfigurations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftConfigServiceServer).ListConfigurations(ctx, req.(*ListRaftConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RaftConfigService_ServiceDesc is the grpc.ServiceDesc for RaftConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaftConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RaftConfigService",
	HandlerType: (*RaftConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutConfiguration",
			Handler:    _RaftConfigService_PutConfiguration_Handler,
		},
		{
			MethodName: "GetConfiguration",
			Handler:    _RaftConfigService_GetConfiguration_Handler,
		},
		{
			MethodName: "ListConfigurations",
			Handler:    _RaftConfigService_ListConfigurations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raft_server.proto",
}
